// Maverick Indonesia — Data Analyst Case Study
// Deck Builder: Jakarta Air Pollution Media Intelligence
// Author: Novindra Prasetio
// Generated by Claude (Cowork) for the candidate to submit

const pptxgen = require("pptxgenjs");
const path = require("path");

const pres = new pptxgen();
pres.layout = "LAYOUT_WIDE"; // 13.3 x 7.5
pres.author = "Novindra Prasetio";
pres.title = "Jakarta Air Pollution — Media Intelligence";
pres.company = "Maverick Indonesia · Data Analyst Case Study";

// ============== DESIGN SYSTEM ==============
const COLOR = {
  navy: "1A2B4A",
  navyDark: "0F1A30",
  orange: "EE7B30",
  orangeLight: "F8B370",
  cream: "F7F5F0",
  white: "FFFFFF",
  red: "D14B3C",
  teal: "4A8B7A",
  textDark: "1A1A1A",
  textMuted: "6B7280",
  textLight: "9CA3AF",
  divider: "E5E1D8",
  cardBg: "FFFFFF",
  warmBg: "FCF9F4",
};

const FONT = {
  header: "Calibri",
  body: "Calibri",
};

// Chart paths (absolute Linux paths)
const CHARTS = "/sessions/funny-jolly-meitner/mnt/Maverick Indonesia/maverick-jakarta-air-pollution/outputs/charts";
const IMG = {
  monthly:    `${CHARTS}/01_monthly_volume.png`,
  augDaily:   `${CHARTS}/02_august_daily.png`,
  wordcloud:  `${CHARTS}/03_wordcloud.png`,
  tier:       `${CHARTS}/04_engagement_tier.png`,
  platform:   `${CHARTS}/05_platform_skew.png`,
};

// Slide dimensions for LAYOUT_WIDE
const W = 13.3;
const H = 7.5;

// ============== HELPERS ==============
function addPageBackground(slide, isDark = false) {
  slide.background = { color: isDark ? COLOR.navy : COLOR.cream };
}

function addFooter(slide, pageNum, totalPages, sectionLabel = "") {
  // Bottom rule
  slide.addShape(pres.shapes.LINE, {
    x: 0.6, y: H - 0.45, w: W - 1.2, h: 0,
    line: { color: COLOR.divider, width: 0.5 }
  });
  // Left footer text
  slide.addText("Jakarta Air Pollution · Maverick Data Analyst Case Study", {
    x: 0.6, y: H - 0.4, w: 8, h: 0.3,
    fontSize: 9, fontFace: FONT.body, color: COLOR.textMuted, margin: 0,
  });
  // Section + page (right)
  slide.addText(`${sectionLabel ? sectionLabel + "  ·  " : ""}${pageNum} / ${totalPages}`, {
    x: W - 4.6, y: H - 0.4, w: 4, h: 0.3,
    fontSize: 9, fontFace: FONT.body, color: COLOR.textMuted, margin: 0, align: "right",
  });
}

function addOrangeBar(slide, x, y, h = 0.6) {
  slide.addShape(pres.shapes.RECTANGLE, {
    x: x, y: y, w: 0.08, h: h,
    fill: { color: COLOR.orange }, line: { color: COLOR.orange, width: 0 },
  });
}

function addTitle(slide, eyebrow, title) {
  // Eyebrow (small uppercase orange label)
  slide.addText(eyebrow.toUpperCase(), {
    x: 0.85, y: 0.5, w: 12, h: 0.3,
    fontSize: 11, fontFace: FONT.body, color: COLOR.orange, bold: true,
    charSpacing: 4, margin: 0,
  });
  // Main title (offset from orange bar at x=0.6 to avoid overlap)
  slide.addText(title, {
    x: 0.85, y: 0.85, w: 12, h: 0.85,
    fontSize: 26, fontFace: FONT.header, color: COLOR.navy, bold: true,
    margin: 0,
  });
}

const TOTAL = 22;

// ============================================================
// SLIDE 1 — COVER
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, true);

  // Background accent: large orange diagonal panel (subtle)
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0, y: 0, w: 0.25, h: H,
    fill: { color: COLOR.orange }, line: { width: 0 },
  });

  // Eyebrow
  s.addText("MAVERICK INDONESIA  ·  DATA ANALYST CASE STUDY", {
    x: 0.9, y: 1.1, w: 11, h: 0.4,
    fontSize: 12, fontFace: FONT.body, color: COLOR.orangeLight, bold: true,
    charSpacing: 5, margin: 0,
  });

  // Main Title
  s.addText("Jakarta Air Pollution", {
    x: 0.9, y: 1.6, w: 12, h: 1.2,
    fontSize: 56, fontFace: FONT.header, color: COLOR.white, bold: true, margin: 0,
  });
  s.addText("Media Intelligence Report", {
    x: 0.9, y: 2.7, w: 12, h: 0.9,
    fontSize: 40, fontFace: FONT.header, color: COLOR.orangeLight, italic: true, margin: 0,
  });

  // Tagline rule
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.9, y: 4.0, w: 1.5, h: 0.04,
    fill: { color: COLOR.orange }, line: { width: 0 },
  });

  // Subtitle / position
  s.addText("From a 4,113-article media wave to a launch strategy:\nwhen, where, and how the client should make its first move.", {
    x: 0.9, y: 4.2, w: 11, h: 1.1,
    fontSize: 18, fontFace: FONT.body, color: COLOR.cream, margin: 0,
  });

  // Author + meta strip
  s.addText([
    { text: "Submitted by  ", options: { color: COLOR.textLight, fontSize: 12 } },
    { text: "Novindra Prasetio", options: { color: COLOR.white, bold: true, fontSize: 14 } },
    { text: "    ·    novindrap@gmail.com    ·    May 2026", options: { color: COLOR.textLight, fontSize: 12 } },
  ], { x: 0.9, y: 6.5, w: 12, h: 0.4, margin: 0 });
}

// ============================================================
// SLIDE 2 — EXECUTIVE SUMMARY
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, false);
  addTitle(s, "Executive Summary", "Tujuh kalimat untuk pengambil keputusan");
  addOrangeBar(s, 0.6, 0.85, 0.85);

  const items = [
    ["01", "Headline Finding", "Polusi udara Jakarta kini bukan lagi sekadar perdebatan regulasi — telah berevolusi menjadi krisis kesehatan berbasis lifestyle yang direspons sebagai ancaman personal."],
    ["02", "The Wave Reality", "Fase kepanikan Agustus yang mendominasi 68,5% publikasi setahun telah runtuh tajam — November tersisa hanya 19 artikel."],
    ["03", "The Opportunity", "Jangan launch sekarang. Gunakan 6 bulan ke depan untuk quiet pre-positioning, lalu eksekusi big-bang akhir Juni 2024 saat puncak kemarau berikutnya."],
    ["04", "The Angle", "Buang jargon kebijakan; bertumpu pada empati keseharian — outlier 25.536 interaksi tercipta dari celotehan kasual selebriti, bukan press conference."],
    ["05", "The How", "Hentikan PR massal. Beralih ke kolaborasi VIP eksklusif: kompas.tv, jaringan Tempo, kompas.com, cnnindonesia.com."],
    ["06", "The Proof", "Jadikan data hardware sebagai konten — rilis Jakarta Pollution Live Index, embed gratis di portal media partner."],
    ["07", "The Measurement", "KPI 3-bulan pasca-launch: 25% Share of Voice di top-5 outlet, +40% brand mention growth, 500 device pre-orders."],
  ];

  // Two-column layout
  const colWidth = 6.0;
  const colGap = 0.3;
  const startX = 0.6;
  const startY = 1.95;
  const itemH = 1.20;

  items.forEach((item, idx) => {
    const col = idx < 4 ? 0 : 1;
    const row = idx < 4 ? idx : idx - 4;
    const x = startX + col * (colWidth + colGap);
    const y = startY + row * itemH;

    // Number badge
    s.addShape(pres.shapes.RECTANGLE, {
      x: x, y: y, w: 0.55, h: 0.55,
      fill: { color: COLOR.orange }, line: { width: 0 },
    });
    s.addText(item[0], {
      x: x, y: y, w: 0.55, h: 0.55,
      fontSize: 14, fontFace: FONT.header, color: COLOR.white, bold: true, align: "center", valign: "middle", margin: 0,
    });
    // Header
    s.addText(item[1], {
      x: x + 0.7, y: y - 0.02, w: colWidth - 0.7, h: 0.35,
      fontSize: 13, fontFace: FONT.header, color: COLOR.navy, bold: true, margin: 0,
    });
    // Body
    s.addText(item[2], {
      x: x + 0.7, y: y + 0.32, w: colWidth - 0.7, h: 0.85,
      fontSize: 10, fontFace: FONT.body, color: COLOR.textDark, margin: 0,
    });
  });

  addFooter(s, 2, TOTAL, "Executive Summary");
}

// ============================================================
// SLIDE 3 — THE BRIEF
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, false);
  addTitle(s, "The Brief", "Konteks: klien, pertanyaan, dan dataset");
  addOrangeBar(s, 0.6, 0.85, 0.85);

  // Left column — Client
  const card = (x, y, w, h, eyebrow, headline, body, accent = COLOR.orange) => {
    s.addShape(pres.shapes.RECTANGLE, {
      x, y, w, h, fill: { color: COLOR.white }, line: { color: COLOR.divider, width: 0.5 },
      shadow: { type: "outer", color: "000000", blur: 8, offset: 2, angle: 90, opacity: 0.06 },
    });
    s.addShape(pres.shapes.RECTANGLE, {
      x, y, w: 0.08, h, fill: { color: accent }, line: { width: 0 },
    });
    s.addText(eyebrow.toUpperCase(), {
      x: x + 0.3, y: y + 0.2, w: w - 0.4, h: 0.25,
      fontSize: 9, fontFace: FONT.body, color: accent, bold: true, charSpacing: 3, margin: 0,
    });
    s.addText(headline, {
      x: x + 0.3, y: y + 0.5, w: w - 0.4, h: 0.7,
      fontSize: 16, fontFace: FONT.header, color: COLOR.navy, bold: true, margin: 0,
    });
    s.addText(body, {
      x: x + 0.3, y: y + 1.25, w: w - 0.4, h: h - 1.4,
      fontSize: 11, fontFace: FONT.body, color: COLOR.textDark, margin: 0, valign: "top",
    });
  };

  card(0.6, 1.95, 4.0, 4.6, "Klien",
    "Air Quality Hardware Startup",
    "Startup Jakarta yang membuat alat ukur PM2.5 / AQI portable.\n\nProduk teknis solid, namun awareness publik masih rendah.\n\nMembutuhkan strategi PR yang tepat-momentum: kapan launch, lewat siapa, dan dengan narasi apa.",
    COLOR.orange);

  card(4.85, 1.95, 4.0, 4.6, "Pertanyaan Inti",
    "Is the wave still alive — or already gone?",
    "Klien melihat ledakan pemberitaan polusi Jakarta di tahun 2023.\n\nPertanyaan: apakah momentum media masih relevan untuk dimanfaatkan, atau sudah lewat?\n\nKonsekuensi: keputusan timing peluncuran kampanye awareness yang akan menentukan ROI marketing.",
    COLOR.red);

  card(9.1, 1.95, 3.6, 4.6, "Dataset",
    "4,113 News Articles",
    "Periode: Jan – Nov 2023 (11 bulan).\n\nSumber: media monitoring export.\n\nKolom: Published, Headline, Website, Twitter Influencer Shares, Total Facebook, Total Interactions.\n\nCaveats sesuai brief: LinkedIn = tracking error (drop), 11.7% artikel 0-interaksi.",
    COLOR.teal);

  addFooter(s, 3, TOTAL, "Context");
}

// ============================================================
// SLIDE 4 — METHODOLOGY & DATA QUALITY
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, false);
  addTitle(s, "Methodology", "Bagaimana kami membersihkan dan memperlakukan data");
  addOrangeBar(s, 0.6, 0.85, 0.85);

  // Method cards
  const m = (x, y, w, h, num, title, body) => {
    s.addShape(pres.shapes.RECTANGLE, {
      x, y, w, h, fill: { color: COLOR.white }, line: { color: COLOR.divider, width: 0.5 },
    });
    s.addShape(pres.shapes.OVAL, {
      x: x + 0.3, y: y + 0.3, w: 0.55, h: 0.55,
      fill: { color: COLOR.navy }, line: { width: 0 },
    });
    s.addText(num, {
      x: x + 0.3, y: y + 0.3, w: 0.55, h: 0.55,
      fontSize: 14, fontFace: FONT.header, color: COLOR.white, bold: true, align: "center", valign: "middle", margin: 0,
    });
    s.addText(title, {
      x: x + 1.0, y: y + 0.32, w: w - 1.2, h: 0.4,
      fontSize: 13, fontFace: FONT.header, color: COLOR.navy, bold: true, margin: 0,
    });
    s.addText(body, {
      x: x + 0.3, y: y + 1.05, w: w - 0.5, h: h - 1.2,
      fontSize: 10.5, fontFace: FONT.body, color: COLOR.textDark, margin: 0, valign: "top",
    });
  };

  m(0.6, 1.95, 3.0, 2.4, "1", "Timezone Handling",
    "Semua timestamp di-parse ke Asia/Jakarta sebelum grouping. Mencegah off-by-one error di batas hari/bulan.");
  m(3.75, 1.95, 3.0, 2.4, "2", "Duplicate Treatment",
    "119 duplikat link & 172 duplikat headline diperiksa manual. Yang nilainya identik di-drop; yang berbeda timestamp/interaksi → digabungkan.");
  m(6.9, 1.95, 3.0, 2.4, "3", "Zero-Interaction Articles",
    "482 artikel (11.7%) dengan 0 interaksi diperlakukan sebagai noise pemberitaan tanpa pickup sosial — tetap ada di volume count, dilabel terpisah saat menghitung engagement.");
  m(10.05, 1.95, 2.65, 2.4, "4", "LinkedIn Dropped",
    "Sesuai brief — tracking error. Tidak masuk perhitungan apa pun.");

  // Caveats / Limitations strip
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.6, y: 4.6, w: 12.1, h: 1.95,
    fill: { color: COLOR.warmBg }, line: { color: COLOR.divider, width: 0.5 },
  });
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.6, y: 4.6, w: 0.08, h: 1.95,
    fill: { color: COLOR.red }, line: { width: 0 },
  });
  s.addText("KETERBATASAN ANALISIS", {
    x: 0.85, y: 4.75, w: 12, h: 0.3,
    fontSize: 10, fontFace: FONT.body, color: COLOR.red, bold: true, charSpacing: 3, margin: 0,
  });
  s.addText([
    { text: "Window 11-bulan tunggal", options: { bold: true, color: COLOR.navy } },
    { text: " — tidak ada baseline tahun lain untuk membandingkan apakah pola Agustus 2023 unik atau berulang.", options: { color: COLOR.textDark } },
    { text: "    ·    ", options: { color: COLOR.textMuted } },
    { text: "Tidak ada sentiment score", options: { bold: true, color: COLOR.navy } },
    { text: " — klasifikasi tone berbasis pembacaan headline manual.", options: { color: COLOR.textDark } },
    { text: "    ·    ", options: { color: COLOR.textMuted } },
    { text: "Tidak ada data demografi audience per outlet", options: { bold: true, color: COLOR.navy } },
    { text: " — asumsi audience type berbasis pola distribusi FB vs Twitter Influencer Shares.", options: { color: COLOR.textDark } },
  ], { x: 0.85, y: 5.1, w: 11.7, h: 1.4, fontSize: 11, fontFace: FONT.body, margin: 0, valign: "top" });

  addFooter(s, 4, TOTAL, "Methodology");
}

// ============================================================
// SLIDE 5 — TASK 1 DIVIDER
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, true);

  s.addShape(pres.shapes.RECTANGLE, {
    x: 0, y: 0, w: 0.25, h: H,
    fill: { color: COLOR.orange }, line: { width: 0 },
  });

  s.addText("TASK 01", {
    x: 0.9, y: 2.2, w: 8, h: 0.5,
    fontSize: 14, fontFace: FONT.body, color: COLOR.orange, bold: true, charSpacing: 5, margin: 0,
  });
  s.addText("Coverage Volume\n& Trend", {
    x: 0.9, y: 2.7, w: 12, h: 2.2,
    fontSize: 56, fontFace: FONT.header, color: COLOR.white, bold: true, margin: 0,
  });

  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.9, y: 5.0, w: 1.5, h: 0.04,
    fill: { color: COLOR.orange }, line: { width: 0 },
  });
  s.addText("Memetakan kapan gelombang itu memuncak,\nseberapa besar, dan kapan ia memudar.", {
    x: 0.9, y: 5.15, w: 12, h: 0.9,
    fontSize: 18, fontFace: FONT.body, color: COLOR.cream, italic: true, margin: 0,
  });
}

// ============================================================
// SLIDE 6 — 1.1 Monthly Volume
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, false);
  addTitle(s, "Task 1.1  ·  Monthly Volume", "Agustus 2023: ledakan tunggal yang menelan setahun publikasi");
  addOrangeBar(s, 0.6, 0.85, 0.85);

  // Chart image (left)
  s.addImage({
    path: IMG.monthly,
    x: 0.6, y: 1.95, w: 8.2, h: 4.2,
  });

  // Right sidebar — stat callouts
  const sx = 9.1;
  const stat = (y, num, label) => {
    s.addText(num, {
      x: sx, y, w: 3.6, h: 0.7,
      fontSize: 32, fontFace: FONT.header, color: COLOR.orange, bold: true, margin: 0,
    });
    s.addText(label, {
      x: sx, y: y + 0.7, w: 3.6, h: 0.55,
      fontSize: 10, fontFace: FONT.body, color: COLOR.textDark, margin: 0,
    });
  };

  stat(2.0, "68.5%", "dari seluruh artikel selama 11 bulan tercetak hanya di Agustus 2023.");
  stat(3.4, "21.8×", "lipat dari rata-rata bulanan (~129 artikel) di 10 bulan lainnya.");
  stat(4.8, "−99%", "kontraksi volume dari Agustus (2.819) ke November (19) — wave sudah mati.");

  // Bottom insight bar
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.6, y: 6.25, w: 12.1, h: 0.65,
    fill: { color: COLOR.navy }, line: { width: 0 },
  });
  s.addText([
    { text: "Insight:  ", options: { bold: true, color: COLOR.orange } },
    { text: "Bulan Agustus mendominasi karena kombinasi krisis musiman (kemarau + El Niño) dan rentetan pemicu kontroversi politik — namun kurva pasca-Agustus menunjukkan bahwa atensi publik telah pindah ke topik lain.", options: { color: COLOR.white } },
  ], { x: 0.85, y: 6.27, w: 11.7, h: 0.6, fontSize: 11, fontFace: FONT.body, margin: 0, valign: "middle" });

  addFooter(s, 6, TOTAL, "Task 1 — Volume & Trend");
}

// ============================================================
// SLIDE 7 — 1.2 August Daily Three Phases
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, false);
  addTitle(s, "Task 1.2  ·  August Deep-Dive", "Tiga fase krisis dalam 30 hari — bukan satu peristiwa tunggal");
  addOrangeBar(s, 0.6, 0.85, 0.85);

  // Chart full width on top
  s.addImage({
    path: IMG.augDaily,
    x: 0.6, y: 1.95, w: 12.1, h: 3.4,
  });

  // 3 phase cards beneath
  const phaseCard = (x, color, num, dates, title, body) => {
    s.addShape(pres.shapes.RECTANGLE, {
      x: x, y: 5.5, w: 3.95, h: 1.55,
      fill: { color: COLOR.white }, line: { color: COLOR.divider, width: 0.5 },
    });
    s.addShape(pres.shapes.RECTANGLE, {
      x: x, y: 5.5, w: 0.08, h: 1.55,
      fill: { color: color }, line: { width: 0 },
    });
    s.addText(num, {
      x: x + 0.25, y: 5.6, w: 0.6, h: 0.3,
      fontSize: 10, fontFace: FONT.body, color: color, bold: true, charSpacing: 2, margin: 0,
    });
    s.addText(dates, {
      x: x + 1.0, y: 5.6, w: 2.9, h: 0.3,
      fontSize: 9, fontFace: FONT.body, color: COLOR.textMuted, margin: 0, align: "right",
    });
    s.addText(title, {
      x: x + 0.25, y: 5.85, w: 3.65, h: 0.35,
      fontSize: 12, fontFace: FONT.header, color: COLOR.navy, bold: true, margin: 0,
    });
    s.addText(body, {
      x: x + 0.25, y: 6.2, w: 3.65, h: 0.85,
      fontSize: 9, fontFace: FONT.body, color: COLOR.textDark, margin: 0, valign: "top",
    });
  };

  phaseCard(0.6, COLOR.orange, "PHASE 1", "14–16 Agustus",
    "First Viral Peak (205/hari)",
    "Berita Jokowi batuk 4 minggu + KLHK menyebut polusi sebagai 'framing' → respons emosional & protes warga di Balai Kota.");
  phaseCard(4.7, COLOR.red, "PHASE 2", "24–25 Agustus",
    "Solutions Controversy (206/hari)",
    "Pemerintah semprot water cannon — dikritik IDI sebagai langkah tidak efektif. KLHK alihkan fokus ke industri.");
  phaseCard(8.75, COLOR.teal, "PHASE 3", "28–31 Agustus",
    "Govt Intervention (223/hari)",
    "Klimaks politis: Jokowi resmi tunjuk Luhut. Narasi bergeser dari kepanikan ke 'krisis prioritas nasional'.");

  addFooter(s, 7, TOTAL, "Task 1 — Volume & Trend");
}

// ============================================================
// SLIDE 8 — 1.3 The Trigger Themes
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, false);
  addTitle(s, "Task 1.3  ·  The Trigger", "Apa yang sebenarnya memicu ledakan Agustus?");
  addOrangeBar(s, 0.6, 0.85, 0.85);

  // Wordcloud (left)
  s.addImage({
    path: IMG.wordcloud,
    x: 0.6, y: 1.95, w: 6.5, h: 3.6,
  });
  s.addText("Word Cloud — Headlines 11–16 Agustus 2023", {
    x: 0.6, y: 5.6, w: 6.5, h: 0.3,
    fontSize: 9, fontFace: FONT.body, color: COLOR.textMuted, italic: true, align: "center", margin: 0,
  });

  // Right — theme tags + insight
  const themeTag = (y, color, tag, desc) => {
    s.addShape(pres.shapes.RECTANGLE, {
      x: 7.4, y, w: 1.7, h: 0.4,
      fill: { color: color }, line: { width: 0 },
    });
    s.addText(tag, {
      x: 7.4, y, w: 1.7, h: 0.4,
      fontSize: 10, fontFace: FONT.header, color: COLOR.white, bold: true, align: "center", valign: "middle", margin: 0,
    });
    s.addText(desc, {
      x: 9.25, y: y + 0.05, w: 3.45, h: 0.7,
      fontSize: 10, fontFace: FONT.body, color: COLOR.textDark, margin: 0, valign: "top",
    });
  };

  s.addText("TEMA DOMINAN", {
    x: 7.4, y: 1.95, w: 5.3, h: 0.3,
    fontSize: 10, fontFace: FONT.body, color: COLOR.navy, bold: true, charSpacing: 3, margin: 0,
  });

  themeTag(2.35, COLOR.red, "health-impact", "Jokowi batuk 4 minggu, anak Sandra Dewi sakit, ancaman ISPA pada anak.");
  themeTag(3.15, COLOR.navy, "politics", "Pernyataan kontroversial KLHK ('framing'), saling sindir tokoh politik.");
  themeTag(3.95, COLOR.teal, "wfh-policy", "Wacana awal kebijakan WFH bagi ASN.");
  themeTag(4.75, COLOR.orange, "industry", "Perdebatan: kendaraan vs PLTU & industri — siapa 'kambing hitam'?");

  // Bottom punchline
  s.addShape(pres.shapes.RECTANGLE, {
    x: 7.4, y: 5.7, w: 5.3, h: 1.0,
    fill: { color: COLOR.navy }, line: { width: 0 },
  });
  s.addText([
    { text: "Punchline:\n", options: { bold: true, color: COLOR.orange, fontSize: 10 } },
    { text: "Polusi meledak bukan karena angka kualitas udara — melainkan karena ", options: { color: COLOR.white, fontSize: 10 } },
    { text: "empati personal", options: { color: COLOR.orangeLight, fontSize: 10, bold: true } },
    { text: " atas masalah kesehatan publik sehari-hari.", options: { color: COLOR.white, fontSize: 10 } },
  ], { x: 7.6, y: 5.8, w: 5.0, h: 0.85, margin: 0, valign: "top" });

  addFooter(s, 8, TOTAL, "Task 1 — Volume & Trend");
}

// ============================================================
// SLIDE 9 — 1.4 September Pivot
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, false);
  addTitle(s, "Task 1.4  ·  The September Pivot", "Audiens lelah blame-game politik, beralih ke survival & solusi");
  addOrangeBar(s, 0.6, 0.85, 0.85);

  // Before / After comparison
  const compareCol = (x, w, side, eyebrow, headline, items, color) => {
    s.addShape(pres.shapes.RECTANGLE, {
      x, y: 1.95, w, h: 4.6,
      fill: { color: COLOR.white }, line: { color: COLOR.divider, width: 0.5 },
    });
    s.addShape(pres.shapes.RECTANGLE, {
      x, y: 1.95, w, h: 0.5,
      fill: { color: color }, line: { width: 0 },
    });
    s.addText(side, {
      x: x + 0.3, y: 1.97, w: w - 0.6, h: 0.45,
      fontSize: 11, fontFace: FONT.body, color: COLOR.white, bold: true, charSpacing: 3, margin: 0, valign: "middle",
    });
    s.addText(eyebrow, {
      x: x + 0.3, y: 1.97, w: w - 0.6, h: 0.45,
      fontSize: 10, fontFace: FONT.body, color: COLOR.white, italic: true, margin: 0, valign: "middle", align: "right",
    });
    s.addText(headline, {
      x: x + 0.3, y: 2.65, w: w - 0.6, h: 0.5,
      fontSize: 16, fontFace: FONT.header, color: COLOR.navy, bold: true, margin: 0,
    });
    const lines = items.map((t, i) => ({
      text: t, options: { bullet: true, breakLine: i < items.length - 1, color: COLOR.textDark, fontSize: 11 }
    }));
    s.addText(lines, {
      x: x + 0.3, y: 3.25, w: w - 0.6, h: 3.2,
      fontFace: FONT.body, margin: 0, valign: "top", paraSpaceAfter: 6,
    });
  };

  compareCol(0.6, 6.0, "AGUSTUS 2023 (BEFORE)", "Drama politik & krisis",
    "Politics + Health Panic",
    [
      "Jokowi tunjuk Luhut menangani polusi (2.856 interaksi)",
      "Anies kritisi subsidi mobil listrik (4.214 interaksi)",
      "KLHK 'framing' & water cannon controversy",
      "ASN WFH wacana reaktif",
    ], COLOR.red);

  compareCol(6.7, 6.0, "SEPTEMBER 2023 (AFTER)", "Lifestyle & survival",
    "Lifestyle + Fatal Health Threat",
    [
      "Kris Dayanti @ Synchronize Festival (25.536 interaksi — outlier #1)",
      "Polusi memperpendek usia Jakartans 4,3 tahun (studi ilmiah)",
      "Korban nyawa & kondisi paru-paru anak-anak",
      "Solusi praktis: air purifier, masker N95, gaya hidup bersih",
    ], COLOR.teal);

  // Bottom insight bar
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.6, y: 6.65, w: 12.1, h: 0.3,
    fill: { color: COLOR.orange }, line: { width: 0 },
  });
  s.addText("Audience attention shifted: from political theater → personal survival. Inilah window narasi yang harus ditangkap.", {
    x: 0.6, y: 6.65, w: 12.1, h: 0.3,
    fontSize: 10, fontFace: FONT.body, color: COLOR.white, bold: true, italic: true, align: "center", valign: "middle", margin: 0,
  });

  addFooter(s, 9, TOTAL, "Task 1 — Volume & Trend");
}

// ============================================================
// SLIDE 10 — TASK 2 DIVIDER
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, true);
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0, y: 0, w: 0.25, h: H, fill: { color: COLOR.orange }, line: { width: 0 },
  });
  s.addText("TASK 02", {
    x: 0.9, y: 2.2, w: 8, h: 0.5,
    fontSize: 14, fontFace: FONT.body, color: COLOR.orange, bold: true, charSpacing: 5, margin: 0,
  });
  s.addText("Engagement\n& Source Analysis", {
    x: 0.9, y: 2.7, w: 12, h: 2.2,
    fontSize: 56, fontFace: FONT.header, color: COLOR.white, bold: true, margin: 0,
  });
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.9, y: 5.0, w: 1.5, h: 0.04, fill: { color: COLOR.orange }, line: { width: 0 },
  });
  s.addText("Volume mengukur seberapa banyak yang ditulis.\nEngagement mengungkap apa yang benar-benar audiens respons.", {
    x: 0.9, y: 5.15, w: 12, h: 0.9,
    fontSize: 18, fontFace: FONT.body, color: COLOR.cream, italic: true, margin: 0,
  });
}

// ============================================================
// SLIDE 11 — 2.1 Power-Law Distribution
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, false);
  addTitle(s, "Task 2.1  ·  Engagement Distribution", "Power-law ekstrem — 0.3% artikel memonopoli viralitas");
  addOrangeBar(s, 0.6, 0.85, 0.85);

  // Chart left
  s.addImage({
    path: IMG.tier,
    x: 0.6, y: 1.95, w: 7.8, h: 4.4,
  });

  // Right — Pareto callout cards
  const sx = 8.7;
  const card = (y, h, color, kpi, label, desc) => {
    s.addShape(pres.shapes.RECTANGLE, {
      x: sx, y, w: 4.0, h, fill: { color: COLOR.white }, line: { color: COLOR.divider, width: 0.5 },
    });
    s.addShape(pres.shapes.RECTANGLE, {
      x: sx, y, w: 0.08, h, fill: { color: color }, line: { width: 0 },
    });
    s.addText(kpi, {
      x: sx + 0.25, y: y + 0.15, w: 3.8, h: 0.55,
      fontSize: 26, fontFace: FONT.header, color: color, bold: true, margin: 0,
    });
    s.addText(label, {
      x: sx + 0.25, y: y + 0.7, w: 3.8, h: 0.3,
      fontSize: 10, fontFace: FONT.header, color: COLOR.navy, bold: true, margin: 0,
    });
    s.addText(desc, {
      x: sx + 0.25, y: y + 1.0, w: 3.8, h: h - 1.05,
      fontSize: 9.5, fontFace: FONT.body, color: COLOR.textDark, margin: 0, valign: "top",
    });
  };

  card(1.95, 1.4, COLOR.red, "63%",
    "Articles get ≤10 interactions",
    "Artikel '0' + '1–10' = 2.583 dari 4.113. Mayoritas absolut nyaris tanpa respons audiens.");
  card(3.45, 1.4, COLOR.orange, "0.3%",
    "Articles capture viral mass",
    "Hanya 11 artikel menembus >1.000 interaksi. Tier elit yang mengontrol percakapan publik.");
  card(4.95, 1.4, COLOR.teal, "Strategic implication",
    "Stop spray-and-pray PR",
    "Sebar press release ke 100+ portal = membuang budget. Fokus 100% sumber daya pada 10–20 top tier publishers yang terbukti memicu interaksi massa.");

  addFooter(s, 11, TOTAL, "Task 2 — Engagement & Source");
}

// ============================================================
// SLIDE 12 — 2.2 The Outlier Kris Dayanti
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, false);
  addTitle(s, "Task 2.2  ·  The Outlier", "25.536 interaksi dari satu komentar kasual selebriti");
  addOrangeBar(s, 0.6, 0.85, 0.85);

  // BIG STAT (left)
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.6, y: 1.95, w: 5.5, h: 4.6,
    fill: { color: COLOR.navy }, line: { width: 0 },
  });
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.6, y: 1.95, w: 5.5, h: 0.08,
    fill: { color: COLOR.orange }, line: { width: 0 },
  });
  s.addText("THE NUMBER", {
    x: 0.85, y: 2.15, w: 5, h: 0.3,
    fontSize: 10, fontFace: FONT.body, color: COLOR.orange, bold: true, charSpacing: 4, margin: 0,
  });
  s.addText("25,536", {
    x: 0.85, y: 2.55, w: 5, h: 1.6,
    fontSize: 84, fontFace: FONT.header, color: COLOR.white, bold: true, margin: 0,
  });
  s.addText("total interactions", {
    x: 0.85, y: 4.2, w: 5, h: 0.4,
    fontSize: 14, fontFace: FONT.body, color: COLOR.cream, italic: true, margin: 0,
  });

  // Comparison
  s.addShape(pres.shapes.LINE, {
    x: 0.85, y: 4.85, w: 4.5, h: 0,
    line: { color: COLOR.orange, width: 1 }
  });
  s.addText([
    { text: "6×", options: { bold: true, color: COLOR.orangeLight, fontSize: 22 } },
    { text: "  lebih besar dari artikel #2", options: { color: COLOR.cream, fontSize: 12 } },
    { text: "\n", options: {} },
    { text: "(Anies — politik mobil listrik · 4.214 interaksi)", options: { color: COLOR.textLight, fontSize: 10, italic: true } },
  ], { x: 0.85, y: 4.95, w: 5, h: 1.2, margin: 0, valign: "top" });

  // Right side — story breakdown
  s.addText("Kris Dayanti Singgung Polusi Udara Jakarta\nSaat Manggung di Synchronize Hari Pertama", {
    x: 6.3, y: 1.95, w: 6.4, h: 1.0,
    fontSize: 16, fontFace: FONT.header, color: COLOR.navy, bold: true, italic: true, margin: 0,
  });
  s.addText("kompas.com  ·  1 September 2023", {
    x: 6.3, y: 2.95, w: 6.4, h: 0.3,
    fontSize: 10, fontFace: FONT.body, color: COLOR.textMuted, margin: 0,
  });

  s.addText("MENGAPA INI MELEDAK", {
    x: 6.3, y: 3.4, w: 6.4, h: 0.3,
    fontSize: 10, fontFace: FONT.body, color: COLOR.orange, bold: true, charSpacing: 3, margin: 0,
  });

  const reason = (y, label, body) => {
    s.addShape(pres.shapes.OVAL, {
      x: 6.3, y, w: 0.18, h: 0.18,
      fill: { color: COLOR.orange }, line: { width: 0 },
    });
    s.addText([
      { text: label + ".  ", options: { bold: true, color: COLOR.navy, fontSize: 11 } },
      { text: body, options: { color: COLOR.textDark, fontSize: 11 } },
    ], { x: 6.6, y: y - 0.06, w: 6.1, h: 0.6, margin: 0, valign: "top" });
  };
  reason(3.85, "Identitas pelaku", "Selebriti relevan, bukan pejabat — relatable & approachable.");
  reason(4.45, "Konteks moment",   "Festival musik raksasa Synchronize → audiens emosional, tinggi engagement.");
  reason(5.05, "Channel",          "100% interaksi dari Facebook → audiens massa akar rumput, bukan elite.");
  reason(5.65, "Format pesan",     "'Singgung' = komentar kasual, bukan press conference yang kaku.");

  // Bottom punchline
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.6, y: 6.65, w: 12.1, h: 0.3,
    fill: { color: COLOR.orange }, line: { width: 0 },
  });
  s.addText("Jakarta audiences respond to human moments, not policy statements.", {
    x: 0.6, y: 6.65, w: 12.1, h: 0.3,
    fontSize: 11, fontFace: FONT.body, color: COLOR.white, bold: true, italic: true, align: "center", valign: "middle", margin: 0,
  });

  addFooter(s, 12, TOTAL, "Task 2 — Engagement & Source");
}

// ============================================================
// SLIDE 13 — 2.3 Two Audiences (FB vs Twitter)
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, false);
  addTitle(s, "Task 2.3  ·  Two Platforms, Two Audiences", "Polarisasi audiens — outlet harus diperlakukan berbeda");
  addOrangeBar(s, 0.6, 0.85, 0.85);

  // Chart (left, larger because tall)
  s.addImage({
    path: IMG.platform,
    x: 0.6, y: 1.95, w: 7.0, h: 5.0,
  });

  // Right — interpretation cards
  const sx = 7.85;

  // Twitter card
  s.addShape(pres.shapes.RECTANGLE, {
    x: sx, y: 1.95, w: 4.85, h: 2.4,
    fill: { color: COLOR.white }, line: { color: COLOR.divider, width: 0.5 },
  });
  s.addShape(pres.shapes.RECTANGLE, {
    x: sx, y: 1.95, w: 0.08, h: 2.4, fill: { color: "1DA1F2" }, line: { width: 0 },
  });
  s.addText("TWITTER-SKEWED  ·  Elite & Analitis", {
    x: sx + 0.25, y: 2.05, w: 4.6, h: 0.3,
    fontSize: 9, fontFace: FONT.body, color: "1DA1F2", bold: true, charSpacing: 3, margin: 0,
  });
  s.addText("metro.tempo.co  ·  tekno.tempo.co  ·  gelora.co", {
    x: sx + 0.25, y: 2.4, w: 4.6, h: 0.4,
    fontSize: 13, fontFace: FONT.header, color: COLOR.navy, bold: true, margin: 0,
  });
  s.addText("Interaksi nyaris 100% dari Twitter influencer (1K+ followers). Audience: jurnalis, pembuat kebijakan, aktivis.", {
    x: sx + 0.25, y: 2.85, w: 4.6, h: 0.6,
    fontSize: 10.5, fontFace: FONT.body, color: COLOR.textDark, margin: 0, valign: "top",
  });
  s.addText([
    { text: "Use for:  ", options: { bold: true, color: COLOR.navy, fontSize: 10 } },
    { text: "credibility, policy pressure, B2B trust signals.", options: { color: COLOR.textDark, fontSize: 10, italic: true } },
  ], { x: sx + 0.25, y: 3.65, w: 4.6, h: 0.55, margin: 0, valign: "top" });

  // Facebook card
  s.addShape(pres.shapes.RECTANGLE, {
    x: sx, y: 4.55, w: 4.85, h: 2.4,
    fill: { color: COLOR.white }, line: { color: COLOR.divider, width: 0.5 },
  });
  s.addShape(pres.shapes.RECTANGLE, {
    x: sx, y: 4.55, w: 0.08, h: 2.4, fill: { color: "4267B2" }, line: { width: 0 },
  });
  s.addText("FACEBOOK-SKEWED  ·  Regional & Massa", {
    x: sx + 0.25, y: 4.65, w: 4.6, h: 0.3,
    fontSize: 9, fontFace: FONT.body, color: "4267B2", bold: true, charSpacing: 3, margin: 0,
  });
  s.addText("bantennews.co.id  ·  prsoloraya.pikiran-rakyat.com  ·  briliobeauty.net", {
    x: sx + 0.25, y: 5.0, w: 4.6, h: 0.6,
    fontSize: 13, fontFace: FONT.header, color: COLOR.navy, bold: true, margin: 0,
  });
  s.addText("Media lokal/regional dan lifestyle — 100% interaksi dari Facebook. Audience: konsumen umum, akar rumput.", {
    x: sx + 0.25, y: 5.65, w: 4.6, h: 0.6,
    fontSize: 10.5, fontFace: FONT.body, color: COLOR.textDark, margin: 0, valign: "top",
  });
  s.addText([
    { text: "Use for:  ", options: { bold: true, color: COLOR.navy, fontSize: 10 } },
    { text: "mass awareness, human-interest virality, product trial sign-ups.", options: { color: COLOR.textDark, fontSize: 10, italic: true } },
  ], { x: sx + 0.25, y: 6.4, w: 4.6, h: 0.5, margin: 0, valign: "top" });

  addFooter(s, 13, TOTAL, "Task 2 — Engagement & Source");
}

// ============================================================
// SLIDE 14 — 2.4 The Sweet Spot — kompas.tv
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, false);
  addTitle(s, "Task 2.4  ·  Source Ranking", "Volume ≠ Engagement — satu outlet menguasai keduanya");
  addOrangeBar(s, 0.6, 0.85, 0.85);

  // Two table-cards
  const tableHeader = (x, w, title, color) => {
    s.addShape(pres.shapes.RECTANGLE, {
      x, y: 1.95, w, h: 0.5, fill: { color: color }, line: { width: 0 },
    });
    s.addText(title, {
      x: x + 0.2, y: 1.95, w: w - 0.4, h: 0.5,
      fontSize: 12, fontFace: FONT.header, color: COLOR.white, bold: true, charSpacing: 2, margin: 0, valign: "middle",
    });
  };

  // LEFT — Top 5 by Volume
  tableHeader(0.6, 5.5, "TOP 5 BY VOLUME (publish terbanyak)", COLOR.textMuted);
  const volRows = [
    ["1", "liputan6.com", "314", "16.9"],
    ["2", "cnnindonesia.com", "306", "56.5"],
    ["3", "idntimes.com", "183", "15.6"],
    ["4", "kompas.tv ★", "164", "97.8"],
    ["5", "health.detik.com", "156", "15.4"],
  ];
  volRows.forEach((r, i) => {
    const y = 2.55 + i * 0.55;
    const isHighlight = r[1].includes("★");
    if (isHighlight) {
      s.addShape(pres.shapes.RECTANGLE, {
        x: 0.6, y, w: 5.5, h: 0.5, fill: { color: COLOR.orangeLight }, line: { width: 0 },
      });
    }
    s.addText(r[0], { x: 0.7, y, w: 0.4, h: 0.5, fontSize: 11, color: COLOR.textMuted, valign: "middle", margin: 0 });
    s.addText(r[1], { x: 1.2, y, w: 2.6, h: 0.5, fontSize: 11.5, color: COLOR.navy, bold: isHighlight, valign: "middle", margin: 0 });
    s.addText(r[2], { x: 3.8, y, w: 0.9, h: 0.5, fontSize: 11, color: COLOR.textDark, valign: "middle", align: "right", margin: 0 });
    s.addText(r[3], { x: 4.8, y, w: 1.2, h: 0.5, fontSize: 11, color: COLOR.textDark, valign: "middle", align: "right", margin: 0 });
  });
  // headers row
  s.addText("articles", { x: 3.8, y: 2.45, w: 0.9, h: 0.25, fontSize: 8, color: COLOR.textMuted, italic: true, align: "right", margin: 0 });
  s.addText("avg eng", { x: 4.8, y: 2.45, w: 1.2, h: 0.25, fontSize: 8, color: COLOR.textMuted, italic: true, align: "right", margin: 0 });

  // RIGHT — Top 5 by Engagement
  tableHeader(7.2, 5.5, "TOP 5 BY AVG ENGAGEMENT (≥20 articles)", COLOR.orange);
  const engRows = [
    ["1", "kompas.com", "66", "399.3"],
    ["2", "suarasurabaya.net", "25", "104.1"],
    ["3", "kompas.tv ★", "164", "97.8"],
    ["4", "cnnindonesia.com", "306", "56.5"],
    ["5", "metro.tempo.co", "35", "53.0"],
  ];
  engRows.forEach((r, i) => {
    const y = 2.55 + i * 0.55;
    const isHighlight = r[1].includes("★");
    if (isHighlight) {
      s.addShape(pres.shapes.RECTANGLE, {
        x: 7.2, y, w: 5.5, h: 0.5, fill: { color: COLOR.orangeLight }, line: { width: 0 },
      });
    }
    s.addText(r[0], { x: 7.3, y, w: 0.4, h: 0.5, fontSize: 11, color: COLOR.textMuted, valign: "middle", margin: 0 });
    s.addText(r[1], { x: 7.8, y, w: 2.6, h: 0.5, fontSize: 11.5, color: COLOR.navy, bold: isHighlight, valign: "middle", margin: 0 });
    s.addText(r[2], { x: 10.4, y, w: 0.9, h: 0.5, fontSize: 11, color: COLOR.textDark, valign: "middle", align: "right", margin: 0 });
    s.addText(r[3], { x: 11.4, y, w: 1.2, h: 0.5, fontSize: 11, color: COLOR.textDark, valign: "middle", align: "right", margin: 0 });
  });
  s.addText("articles", { x: 10.4, y: 2.45, w: 0.9, h: 0.25, fontSize: 8, color: COLOR.textMuted, italic: true, align: "right", margin: 0 });
  s.addText("avg eng", { x: 11.4, y: 2.45, w: 1.2, h: 0.25, fontSize: 8, color: COLOR.textMuted, italic: true, align: "right", margin: 0 });

  // Sweet spot callout
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.6, y: 5.7, w: 12.1, h: 1.25,
    fill: { color: COLOR.navy }, line: { width: 0 },
  });
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.6, y: 5.7, w: 0.08, h: 1.25, fill: { color: COLOR.orange }, line: { width: 0 },
  });
  s.addText("★  THE SWEET SPOT  ·  kompas.tv", {
    x: 0.85, y: 5.85, w: 11, h: 0.4,
    fontSize: 14, fontFace: FONT.header, color: COLOR.orange, bold: true, charSpacing: 2, margin: 0,
  });
  s.addText("Satu-satunya outlet yang masuk Top-5 di KEDUA daftar — peringkat #4 by volume (164 artikel) dan #3 by engagement (avg 97.8). Konsisten produktif sekaligus konsisten beresonansi. Klien wajib menjadikannya Tier-1 VIP partner.", {
    x: 0.85, y: 6.25, w: 11.85, h: 0.65,
    fontSize: 11, fontFace: FONT.body, color: COLOR.white, margin: 0, valign: "top",
  });

  addFooter(s, 14, TOTAL, "Task 2 — Engagement & Source");
}

// ============================================================
// SLIDE 15 — TASK 3 DIVIDER
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, true);
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0, y: 0, w: 0.25, h: H, fill: { color: COLOR.orange }, line: { width: 0 },
  });
  s.addText("TASK 03", {
    x: 0.9, y: 2.2, w: 8, h: 0.5,
    fontSize: 14, fontFace: FONT.body, color: COLOR.orange, bold: true, charSpacing: 5, margin: 0,
  });
  s.addText("Strategic\nRecommendation", {
    x: 0.9, y: 2.7, w: 12, h: 2.2,
    fontSize: 56, fontFace: FONT.header, color: COLOR.white, bold: true, margin: 0,
  });
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.9, y: 5.0, w: 1.5, h: 0.04, fill: { color: COLOR.orange }, line: { width: 0 },
  });
  s.addText("Dari data ke keputusan: kapan launch, pesan apa,\nlewat siapa, dan bagaimana mengukur sukses.", {
    x: 0.9, y: 5.15, w: 12, h: 0.9,
    fontSize: 18, fontFace: FONT.body, color: COLOR.cream, italic: true, margin: 0,
  });
}

// ============================================================
// SLIDE 16 — 3.1 Timing
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, false);
  addTitle(s, "Recommendation 3.1  ·  Timing", "Hybrid strategy — pre-position now, launch loud at next dry-season trigger");
  addOrangeBar(s, 0.6, 0.85, 0.85);

  // Three options laid out as cards
  const optCard = (x, w, label, headline, body, accept, color, accent) => {
    s.addShape(pres.shapes.RECTANGLE, {
      x, y: 1.95, w, h: 4.6,
      fill: { color: COLOR.white }, line: { color: COLOR.divider, width: 0.5 },
    });
    s.addShape(pres.shapes.RECTANGLE, {
      x, y: 1.95, w, h: 0.5, fill: { color: color }, line: { width: 0 },
    });
    s.addText(label, {
      x: x + 0.25, y: 1.97, w: w - 0.5, h: 0.45,
      fontSize: 11, fontFace: FONT.body, color: COLOR.white, bold: true, charSpacing: 3, margin: 0, valign: "middle",
    });
    s.addText(accept ? "★ RECOMMENDED" : "—", {
      x: x + 0.25, y: 1.97, w: w - 0.5, h: 0.45,
      fontSize: 10, fontFace: FONT.body, color: accept ? COLOR.cream : COLOR.textLight, bold: true, italic: true, margin: 0, valign: "middle", align: "right",
    });
    s.addText(headline, {
      x: x + 0.25, y: 2.65, w: w - 0.5, h: 0.5,
      fontSize: 14, fontFace: FONT.header, color: COLOR.navy, bold: true, margin: 0,
    });
    s.addText(body, {
      x: x + 0.25, y: 3.25, w: w - 0.5, h: 3.2,
      fontSize: 10, fontFace: FONT.body, color: COLOR.textDark, margin: 0, valign: "top",
    });
  };

  optCard(0.6, 4.0, "OPSI A — LAUNCH NOW", "Risiko tinggi, ROI rendah",
    "Pro: memori publik masih segar; inventory media murah.\n\nKontra: kurva engagement sudah collapse (716 → 142 → 19); tidak ada amplifier alami; budget terbakar tanpa wave.",
    false, COLOR.red);

  optCard(4.85, 4.0, "OPSI B — WAIT PASIF", "6 bulan dormansi — terlalu mahal",
    "Pro: menunggu pola musim kemarau berikutnya yang predictable.\n\nKontra: 6 bulan diam = momentum tim hilang; kompetitor (Nafas, IQAir) bisa pre-empt; tidak ada relationship building.",
    false, COLOR.textMuted);

  optCard(9.1, 4.0, "OPSI C — HYBRID", "★ Pre-position + Launch loud",
    "Q4 2023 – Q1 2024: bangun relasi jurnalis, dataset historis device, press kit.\n\nMar 2024: seeding via IQAir Annual Report.\n\nLate Jun 2024: big-bang launch saat puncak kemarau berikutnya.",
    true, COLOR.teal);

  // Bottom rationale strip
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.6, y: 6.65, w: 12.1, h: 0.3, fill: { color: COLOR.orange }, line: { width: 0 },
  });
  s.addText("Window kemarau Juni–Sept 2024 adalah trigger yang paling probabilistik — pola musiman Indonesia + siklus El Niño.", {
    x: 0.6, y: 6.65, w: 12.1, h: 0.3,
    fontSize: 11, fontFace: FONT.body, color: COLOR.white, bold: true, italic: true, align: "center", valign: "middle", margin: 0,
  });

  addFooter(s, 16, TOTAL, "Task 3 — Recommendation");
}

// ============================================================
// SLIDE 17 — 3.2 Narrative Angle
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, false);
  addTitle(s, "Recommendation 3.2  ·  Narrative Angle", "Lifestyle-Solutions dengan health undertone — buang jargon kebijakan");
  addOrangeBar(s, 0.6, 0.85, 0.85);

  // Big stance left
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.6, y: 1.95, w: 5.0, h: 4.6, fill: { color: COLOR.navy }, line: { width: 0 },
  });
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.6, y: 1.95, w: 5.0, h: 0.08, fill: { color: COLOR.orange }, line: { width: 0 },
  });
  s.addText("THE STANCE", {
    x: 0.85, y: 2.15, w: 4.5, h: 0.3,
    fontSize: 10, fontFace: FONT.body, color: COLOR.orange, bold: true, charSpacing: 4, margin: 0,
  });
  s.addText("Lifestyle-Solutions", {
    x: 0.85, y: 2.55, w: 4.7, h: 0.85,
    fontSize: 32, fontFace: FONT.header, color: COLOR.white, bold: true, margin: 0,
  });
  s.addText("with health undertone", {
    x: 0.85, y: 3.45, w: 4.7, h: 0.5,
    fontSize: 18, fontFace: FONT.body, color: COLOR.orangeLight, italic: true, margin: 0,
  });

  s.addShape(pres.shapes.LINE, {
    x: 0.85, y: 4.2, w: 4.5, h: 0,
    line: { color: COLOR.orange, width: 1 }
  });
  s.addText("Target: konsumen kelas menengah Jakarta yang merasa polusi sebagai ancaman personal — bukan elit kebijakan.", {
    x: 0.85, y: 4.35, w: 4.5, h: 1.2,
    fontSize: 12, fontFace: FONT.body, color: COLOR.cream, italic: true, margin: 0,
  });
  s.addText("AVOID: political angle, regulatory advocacy, blame-game commentary.", {
    x: 0.85, y: 5.65, w: 4.5, h: 0.6,
    fontSize: 11, fontFace: FONT.body, color: COLOR.red, bold: true, margin: 0,
  });

  // Right — supporting evidence (numbered)
  s.addText("EVIDENCE FROM THE DATA", {
    x: 5.85, y: 1.95, w: 7, h: 0.3,
    fontSize: 10, fontFace: FONT.body, color: COLOR.orange, bold: true, charSpacing: 3, margin: 0,
  });

  const ev = (y, num, title, body) => {
    s.addShape(pres.shapes.RECTANGLE, {
      x: 5.85, y, w: 0.5, h: 0.5, fill: { color: COLOR.navy }, line: { width: 0 },
    });
    s.addText(num, {
      x: 5.85, y, w: 0.5, h: 0.5,
      fontSize: 12, fontFace: FONT.header, color: COLOR.white, bold: true, align: "center", valign: "middle", margin: 0,
    });
    s.addText(title, {
      x: 6.5, y: y - 0.05, w: 6.3, h: 0.35,
      fontSize: 12, fontFace: FONT.header, color: COLOR.navy, bold: true, margin: 0,
    });
    s.addText(body, {
      x: 6.5, y: y + 0.3, w: 6.3, h: 0.65,
      fontSize: 10, fontFace: FONT.body, color: COLOR.textDark, margin: 0, valign: "top",
    });
  };

  ev(2.4, "1", "Outlier Kris Dayanti (25.536 interaksi)",
    "Lifestyle/celebrity moment menang 6× lipat dari artikel kebijakan tertinggi (Anies = 4.214).");
  ev(3.5, "2", "Top 11 articles (>1.000 interaksi) — tier elite",
    "Tidak murni politik. Mix: human-impact, celebrity, viral moments. Policy alone tidak cukup memicu virality.");
  ev(4.6, "3", "51% artikel di tier 1–10 (noise massa)",
    "Termasuk policy reporting standar. Kampanye lifestyle akan memotong noise lebih efektif.");
  ev(5.7, "4", "September pivot ke lifestyle/survival",
    "Pasca-Agustus, top headline bergeser dari 'Luhut tunjuk ASN WFH' → 'polusi perpendek usia 4,3 tahun' & Kris Dayanti.");

  addFooter(s, 17, TOTAL, "Task 3 — Recommendation");
}

// ============================================================
// SLIDE 18 — 3.3 Media Targets
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, false);
  addTitle(s, "Recommendation 3.3  ·  Media Targets", "Empat outlet prioritas — masing-masing dengan peran berbeda");
  addOrangeBar(s, 0.6, 0.85, 0.85);

  const outlet = (x, y, w, h, tier, name, audience, why) => {
    s.addShape(pres.shapes.RECTANGLE, {
      x, y, w, h, fill: { color: COLOR.white }, line: { color: COLOR.divider, width: 0.5 },
      shadow: { type: "outer", color: "000000", blur: 8, offset: 2, angle: 90, opacity: 0.06 },
    });
    s.addShape(pres.shapes.RECTANGLE, {
      x, y, w, h: 0.45, fill: { color: COLOR.navy }, line: { width: 0 },
    });
    s.addText(tier, {
      x: x + 0.2, y: y, w: w - 0.4, h: 0.45,
      fontSize: 10, fontFace: FONT.body, color: COLOR.orange, bold: true, charSpacing: 2, margin: 0, valign: "middle",
    });
    s.addText(name, {
      x: x + 0.25, y: y + 0.55, w: w - 0.5, h: 0.45,
      fontSize: 17, fontFace: FONT.header, color: COLOR.navy, bold: true, margin: 0,
    });
    s.addText(audience, {
      x: x + 0.25, y: y + 1.05, w: w - 0.5, h: 0.3,
      fontSize: 10, fontFace: FONT.body, color: COLOR.orange, italic: true, bold: true, margin: 0,
    });
    s.addText(why, {
      x: x + 0.25, y: y + 1.4, w: w - 0.5, h: h - 1.5,
      fontSize: 10, fontFace: FONT.body, color: COLOR.textDark, margin: 0, valign: "top",
    });
  };

  outlet(0.6, 1.95, 6.0, 2.45, "TIER-1  ·  THE SWEET SPOT  ·  ★ MUST-HAVE", "kompas.tv",
    "Hybrid Audience  ·  164 artikel  ·  avg 97.8 engagement",
    "Anchor outlet — satu-satunya yang masuk Top-5 baik volume maupun engagement. ROI tertinggi: jangkauan tayang tinggi + kualitas interaksi terjaga. Ideal untuk Live Index widget & feature stories.");

  outlet(6.7, 1.95, 6.0, 2.45, "TIER-2  ·  MASS AWARENESS  ·  FB-SKEWED", "kompas.com",
    "Mass Audience  ·  66 artikel  ·  avg 399.3 engagement",
    "Avg engagement #1 di seluruh dataset — tempat outlier Kris Dayanti meledak. Channel utama untuk seeding human-interest stories di Facebook akar rumput.");

  outlet(0.6, 4.55, 6.0, 2.45, "TIER-2  ·  CREDIBILITY  ·  TW-SKEWED", "cnnindonesia.com",
    "Elite Audience  ·  306 artikel  ·  avg 56.5 engagement",
    "Volume tinggi + engagement solid. Audience jurnalis dan aktivis Twitter — sempurna untuk thought-leadership pieces dan distribusi data report kualitas udara.");

  outlet(6.7, 4.55, 6.0, 2.45, "TIER-3  ·  POLICY PRESSURE  ·  TW-SKEWED", "Tempo Network (metro/tekno/data)",
    "Elite Audience  ·  60+ artikel  ·  avg 50–100 engagement",
    "Distribusi opini terbesar di Twitter elit. Cocok untuk advokasi kebijakan & framing publik bila kampanye butuh leverage struktural.");

  addFooter(s, 18, TOTAL, "Task 3 — Recommendation");
}

// ============================================================
// SLIDE 19 — 3.4 Data as Content
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, false);
  addTitle(s, "Recommendation 3.4  ·  Data as Content", "Jakarta Pollution Live Index — buat jurnalis datang ke kita");
  addOrangeBar(s, 0.6, 0.85, 0.85);

  // Concept block (left, large)
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.6, y: 1.95, w: 5.5, h: 4.6, fill: { color: COLOR.navy }, line: { width: 0 },
  });
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.6, y: 1.95, w: 5.5, h: 0.08, fill: { color: COLOR.orange }, line: { width: 0 },
  });
  s.addText("THE CONCEPT", {
    x: 0.85, y: 2.15, w: 5, h: 0.3,
    fontSize: 10, fontFace: FONT.body, color: COLOR.orange, bold: true, charSpacing: 4, margin: 0,
  });
  s.addText("Jakarta Pollution\nLive Index", {
    x: 0.85, y: 2.55, w: 5, h: 1.5,
    fontSize: 28, fontFace: FONT.header, color: COLOR.white, bold: true, margin: 0,
  });
  s.addShape(pres.shapes.LINE, {
    x: 0.85, y: 4.15, w: 4.5, h: 0,
    line: { color: COLOR.orange, width: 1 }
  });
  s.addText("Dasbor data hyper-local yang diagregasi real-time dari sensor device pengguna klien — disindikasi seperti laporan BMKG.\n\nPositioning: \"Powered by [Klien]\" sebagai data authority independen.", {
    x: 0.85, y: 4.3, w: 5, h: 2.2,
    fontSize: 12, fontFace: FONT.body, color: COLOR.cream, margin: 0, valign: "top",
  });

  // Right — 3 execution steps
  s.addText("EXECUTION STEPS", {
    x: 6.4, y: 1.95, w: 6, h: 0.3,
    fontSize: 10, fontFace: FONT.body, color: COLOR.orange, bold: true, charSpacing: 3, margin: 0,
  });

  const step = (y, num, title, body) => {
    s.addShape(pres.shapes.OVAL, {
      x: 6.4, y, w: 0.55, h: 0.55, fill: { color: COLOR.orange }, line: { width: 0 },
    });
    s.addText(num, {
      x: 6.4, y, w: 0.55, h: 0.55,
      fontSize: 16, fontFace: FONT.header, color: COLOR.white, bold: true, align: "center", valign: "middle", margin: 0,
    });
    s.addText(title, {
      x: 7.1, y: y - 0.05, w: 5.6, h: 0.4,
      fontSize: 13, fontFace: FONT.header, color: COLOR.navy, bold: true, margin: 0,
    });
    s.addText(body, {
      x: 7.1, y: y + 0.32, w: 5.6, h: 1.0,
      fontSize: 10.5, fontFace: FONT.body, color: COLOR.textDark, margin: 0, valign: "top",
    });
  };

  step(2.4, "1", "Integrasi Data API",
    "Tim Engineering bangun dasbor publik (website widget) menampilkan data AQI/PM2.5 hyper-local berbasis sensor komunitas pengguna.");
  step(4.0, "2", "Media Partnership",
    "Pitch agar widget ditanam permanen di halaman depan portal partner (kompas.tv, cnnindonesia.com) dengan label \"Powered by [Klien]\".");
  step(5.6, "3", "Automated Press Alerts",
    "Sistem email otomatis mengirim Early Warning ke jurnalis partner saat indeks menyentuh zona fatal — mereka proaktif minta wawancara dari ahli klien.");

  addFooter(s, 19, TOTAL, "Task 3 — Recommendation");
}

// ============================================================
// SLIDE 20 — 3.5 AMEC IEF
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, false);
  addTitle(s, "Recommendation 3.5  ·  AMEC IEF Plan", "Pengukuran sukses: Outputs → Outtakes → Outcomes");
  addOrangeBar(s, 0.6, 0.85, 0.85);

  const amecCol = (x, w, color, label, question, items) => {
    // Header
    s.addShape(pres.shapes.RECTANGLE, {
      x, y: 1.95, w, h: 0.7, fill: { color: color }, line: { width: 0 },
    });
    s.addText(label, {
      x: x + 0.25, y: 1.97, w: w - 0.5, h: 0.4,
      fontSize: 14, fontFace: FONT.header, color: COLOR.white, bold: true, charSpacing: 2, margin: 0,
    });
    s.addText(question, {
      x: x + 0.25, y: 2.32, w: w - 0.5, h: 0.3,
      fontSize: 10, fontFace: FONT.body, color: COLOR.cream, italic: true, margin: 0,
    });
    // Body
    s.addShape(pres.shapes.RECTANGLE, {
      x, y: 2.75, w, h: 4.2,
      fill: { color: COLOR.white }, line: { color: COLOR.divider, width: 0.5 },
    });
    const lines = items.map((t, i) => ({
      text: t, options: { bullet: true, breakLine: i < items.length - 1, color: COLOR.textDark, fontSize: 11 },
    }));
    s.addText(lines, {
      x: x + 0.3, y: 2.95, w: w - 0.5, h: 3.85,
      fontFace: FONT.body, margin: 0, valign: "top", paraSpaceAfter: 8,
    });
  };

  amecCol(0.6, 4.0, COLOR.navy, "OUTPUTS", "Apa yang kita produksi?", [
    "1× Live Index API Widget (kolaborasi media partner)",
    "2× sesi Pollution Diary (KOL collab, durasi 7 hari)",
    "10× Media Exclusive Briefing (jurnalis elit Q1–Q2)",
    "1× Annual Air Citizen Report (dry season trigger)",
    "5× press releases bertahap selama 6 bulan",
  ]);

  amecCol(4.75, 4.0, COLOR.orange, "OUTTAKES", "Apa yang berubah di benak audience?", [
    "Brand recall sebagai \"pelindung pernafasan warga\"",
    "Asosiasi brand dengan personal air data layer",
    "Jurnalis menjadikan brand sebagai referensi data polusi independen (data authority)",
    "Konsumen menengah Jakarta mengenali fitur device sebagai everyday tool, bukan gadget niche",
  ]);

  amecCol(8.9, 3.8, COLOR.teal, "OUTCOMES", "Apa yang berubah di dunia nyata? (3-bulan pasca-launch)", [
    "Share of Voice 25% di top-5 target outlet (Q3 2024)",
    "Brand mention growth +40% YoY per Agustus 2024",
    "Konversi 500+ unit device pre-order / trial sign-up dari traffic earned media",
  ]);

  addFooter(s, 20, TOTAL, "Task 3 — Recommendation");
}

// ============================================================
// SLIDE 21 — ROADMAP
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, false);
  addTitle(s, "The Roadmap", "Dari hari ini ke launch-day Juni 2024 — 6 bulan persiapan, 3 bulan eksekusi");
  addOrangeBar(s, 0.6, 0.85, 0.85);

  // Timeline base
  const tlY = 4.0;
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.8, y: tlY, w: 11.7, h: 0.08, fill: { color: COLOR.navy }, line: { width: 0 },
  });

  const milestone = (x, label, headline, body, color, positionAbove = true) => {
    // Dot
    s.addShape(pres.shapes.OVAL, {
      x: x - 0.13, y: tlY - 0.09, w: 0.3, h: 0.3, fill: { color: color }, line: { color: COLOR.white, width: 2 },
    });
    // Label below dot
    s.addText(label, {
      x: x - 1.3, y: tlY + 0.3, w: 2.6, h: 0.3,
      fontSize: 10, fontFace: FONT.body, color: color, bold: true, charSpacing: 2, align: "center", margin: 0,
    });
    // Card
    const cardY = positionAbove ? tlY - 2.0 : tlY + 0.7;
    s.addShape(pres.shapes.RECTANGLE, {
      x: x - 1.3, y: cardY, w: 2.6, h: 1.85,
      fill: { color: COLOR.white }, line: { color: COLOR.divider, width: 0.5 },
    });
    s.addShape(pres.shapes.RECTANGLE, {
      x: x - 1.3, y: cardY, w: 2.6, h: 0.08,
      fill: { color: color }, line: { width: 0 },
    });
    s.addText(headline, {
      x: x - 1.2, y: cardY + 0.15, w: 2.4, h: 0.5,
      fontSize: 12, fontFace: FONT.header, color: COLOR.navy, bold: true, margin: 0,
    });
    s.addText(body, {
      x: x - 1.2, y: cardY + 0.7, w: 2.4, h: 1.1,
      fontSize: 9.5, fontFace: FONT.body, color: COLOR.textDark, margin: 0, valign: "top",
    });
    // Connector line
    s.addShape(pres.shapes.LINE, {
      x: x, y: positionAbove ? cardY + 1.85 : tlY + 0.07,
      w: 0, h: positionAbove ? tlY - (cardY + 1.85) : cardY - (tlY + 0.07),
      line: { color: COLOR.divider, width: 0.75, dashType: "dash" }
    });
  };

  milestone(2.0, "Q4 2023 – Q1 2024", "Pre-Position",
    "Bangun relasi jurnalis kompas.tv & Tempo. Audit dataset device historis. Draft press kit & data API.",
    COLOR.textMuted, true);

  milestone(5.0, "Maret 2024", "Seed Trigger",
    "Rilis IQAir Annual Report sebagai mini-trigger. Soft-launch Live Index widget dengan 1 outlet.",
    COLOR.teal, false);

  milestone(8.0, "Juni 2024", "Big-Bang Launch",
    "Puncak kemarau berikutnya — full activation: Live Index public, Pollution Diary KOL, 10 media briefing.",
    COLOR.orange, true);

  milestone(11.0, "Sept 2024", "Measure & Iterate",
    "Pengukuran KPI 3-bulan: 25% SoV, +40% brand mention, 500 device sign-ups. Iterate untuk kemarau 2025.",
    COLOR.navy, false);

  addFooter(s, 21, TOTAL, "Roadmap");
}

// ============================================================
// SLIDE 22 — CLOSING
// ============================================================
{
  const s = pres.addSlide();
  addPageBackground(s, true);
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0, y: 0, w: 0.25, h: H, fill: { color: COLOR.orange }, line: { width: 0 },
  });

  s.addText("THANK YOU", {
    x: 0.9, y: 1.6, w: 12, h: 0.6,
    fontSize: 18, fontFace: FONT.body, color: COLOR.orange, bold: true, charSpacing: 8, margin: 0,
  });

  s.addText("Open for questions,\nchallenges, and disagreements.", {
    x: 0.9, y: 2.3, w: 12, h: 2.0,
    fontSize: 44, fontFace: FONT.header, color: COLOR.white, bold: true, italic: true, margin: 0,
  });

  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.9, y: 4.8, w: 1.5, h: 0.04, fill: { color: COLOR.orange }, line: { width: 0 },
  });

  s.addText("\"The data has a story. I committed to one.\nI hope this convinces you it's the right one.\"", {
    x: 0.9, y: 5.0, w: 11, h: 1.0,
    fontSize: 16, fontFace: FONT.body, color: COLOR.cream, italic: true, margin: 0,
  });

  // Contact strip
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.9, y: 6.5, w: 11.5, h: 0.04, fill: { color: COLOR.divider }, line: { width: 0 },
  });
  s.addText([
    { text: "Novindra Prasetio", options: { bold: true, color: COLOR.white, fontSize: 14 } },
    { text: "    ·    novindrap@gmail.com    ·    GitHub: maverick-jakarta-air-pollution    ·    May 2026", options: { color: COLOR.textLight, fontSize: 11 } },
  ], { x: 0.9, y: 6.65, w: 12, h: 0.4, margin: 0 });
}

// ============================================================
// SAVE
// ============================================================
const outPath = "/sessions/funny-jolly-meitner/mnt/Maverick Indonesia/maverick-jakarta-air-pollution/deck/Maverick_Case_Study_Novindra.pptx";
pres.writeFile({ fileName: outPath }).then(fn => {
  console.log("✅ Deck saved:", fn);
}).catch(e => {
  console.error("❌ Error:", e);
});
